### ISSUE TITLE
Cambios de Respuesta

### ISSUE THREAD

**Issue by sachakantor** [cristianmiranda/fulbo11bot#1]
En caso de cambiar de respuesta, no se registra si es "baja" o si debe ser ultimo en el ranking. 

En ambos casos se debe registrar la anticipación respecto de la hora del partido.

Tener en cuenta sucesivos cambios de respuesta.

**Comment by cristianmiranda** [comment]
Ya se agregó baja como nuevo estado de confirmación. Se creará un issue nuevo para timestamp.
